# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_jogo_da_forca.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_JogodaForca(object):
    def setupUi(self, JogodaForca):
        JogodaForca.setObjectName("JogodaForca")
        JogodaForca.resize(679, 600)
        self.centralwidget = QtWidgets.QWidget(JogodaForca)
        self.centralwidget.setObjectName("centralwidget")
        self.labAlfabeto = QtWidgets.QLabel(self.centralwidget)
        self.labAlfabeto.setGeometry(QtCore.QRect(10, 430, 77, 16))
        self.labAlfabeto.setObjectName("labAlfabeto")
        self.labForca = QtWidgets.QLabel(self.centralwidget)
        self.labForca.setGeometry(QtCore.QRect(11, 47, 641, 361))
        self.labForca.setObjectName("labForca")
        self.labErros = QtWidgets.QLabel(self.centralwidget)
        self.labErros.setGeometry(QtCore.QRect(11, 11, 91, 16))
        self.labErros.setObjectName("labErros")
        self.btnA = QtWidgets.QPushButton(self.centralwidget)
        self.btnA.setGeometry(QtCore.QRect(11, 478, 45, 28))
        self.btnA.setObjectName("btnA")
        self.btnB = QtWidgets.QPushButton(self.centralwidget)
        self.btnB.setGeometry(QtCore.QRect(62, 478, 44, 28))
        self.btnB.setObjectName("btnB")
        self.btnG = QtWidgets.QPushButton(self.centralwidget)
        self.btnG.setGeometry(QtCore.QRect(314, 478, 44, 28))
        self.btnG.setObjectName("btnG")
        self.btnF = QtWidgets.QPushButton(self.centralwidget)
        self.btnF.setGeometry(QtCore.QRect(263, 478, 45, 28))
        self.btnF.setObjectName("btnF")
        self.btnC = QtWidgets.QPushButton(self.centralwidget)
        self.btnC.setGeometry(QtCore.QRect(112, 478, 45, 28))
        self.btnC.setObjectName("btnC")
        self.btnD = QtWidgets.QPushButton(self.centralwidget)
        self.btnD.setGeometry(QtCore.QRect(163, 478, 44, 28))
        self.btnD.setObjectName("btnD")
        self.btnE = QtWidgets.QPushButton(self.centralwidget)
        self.btnE.setGeometry(QtCore.QRect(213, 478, 44, 28))
        self.btnE.setObjectName("btnE")
        self.btnH = QtWidgets.QPushButton(self.centralwidget)
        self.btnH.setGeometry(QtCore.QRect(364, 478, 45, 28))
        self.btnH.setObjectName("btnH")
        self.btnO = QtWidgets.QPushButton(self.centralwidget)
        self.btnO.setGeometry(QtCore.QRect(62, 512, 44, 28))
        self.btnO.setObjectName("btnO")
        self.btnN = QtWidgets.QPushButton(self.centralwidget)
        self.btnN.setGeometry(QtCore.QRect(11, 512, 45, 28))
        self.btnN.setObjectName("btnN")
        self.btnL = QtWidgets.QPushButton(self.centralwidget)
        self.btnL.setGeometry(QtCore.QRect(566, 478, 44, 28))
        self.btnL.setObjectName("btnL")
        self.btnM = QtWidgets.QPushButton(self.centralwidget)
        self.btnM.setGeometry(QtCore.QRect(616, 478, 44, 28))
        self.btnM.setObjectName("btnM")
        self.btnP = QtWidgets.QPushButton(self.centralwidget)
        self.btnP.setGeometry(QtCore.QRect(112, 512, 45, 28))
        self.btnP.setObjectName("btnP")
        self.btnJ = QtWidgets.QPushButton(self.centralwidget)
        self.btnJ.setGeometry(QtCore.QRect(465, 478, 44, 28))
        self.btnJ.setObjectName("btnJ")
        self.btnK = QtWidgets.QPushButton(self.centralwidget)
        self.btnK.setGeometry(QtCore.QRect(515, 478, 45, 28))
        self.btnK.setObjectName("btnK")
        self.btnI = QtWidgets.QPushButton(self.centralwidget)
        self.btnI.setGeometry(QtCore.QRect(415, 478, 44, 28))
        self.btnI.setObjectName("btnI")
        self.btnW = QtWidgets.QPushButton(self.centralwidget)
        self.btnW.setGeometry(QtCore.QRect(465, 512, 44, 28))
        self.btnW.setObjectName("btnW")
        self.btnV = QtWidgets.QPushButton(self.centralwidget)
        self.btnV.setGeometry(QtCore.QRect(415, 512, 44, 28))
        self.btnV.setObjectName("btnV")
        self.btnT = QtWidgets.QPushButton(self.centralwidget)
        self.btnT.setGeometry(QtCore.QRect(314, 512, 44, 28))
        self.btnT.setObjectName("btnT")
        self.btnU = QtWidgets.QPushButton(self.centralwidget)
        self.btnU.setGeometry(QtCore.QRect(364, 512, 45, 28))
        self.btnU.setObjectName("btnU")
        self.btnX = QtWidgets.QPushButton(self.centralwidget)
        self.btnX.setGeometry(QtCore.QRect(515, 512, 45, 28))
        self.btnX.setObjectName("btnX")
        self.btnR = QtWidgets.QPushButton(self.centralwidget)
        self.btnR.setGeometry(QtCore.QRect(213, 512, 44, 28))
        self.btnR.setObjectName("btnR")
        self.btnS = QtWidgets.QPushButton(self.centralwidget)
        self.btnS.setGeometry(QtCore.QRect(263, 512, 45, 28))
        self.btnS.setObjectName("btnS")
        self.btnY = QtWidgets.QPushButton(self.centralwidget)
        self.btnY.setGeometry(QtCore.QRect(566, 512, 44, 28))
        self.btnY.setObjectName("btnY")
        self.btnQ = QtWidgets.QPushButton(self.centralwidget)
        self.btnQ.setGeometry(QtCore.QRect(163, 512, 44, 28))
        self.btnQ.setObjectName("btnQ")
        self.btnZ = QtWidgets.QPushButton(self.centralwidget)
        self.btnZ.setGeometry(QtCore.QRect(616, 512, 44, 28))
        self.btnZ.setObjectName("btnZ")
        JogodaForca.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JogodaForca)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 679, 22))
        self.menubar.setObjectName("menubar")
        JogodaForca.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JogodaForca)
        self.statusbar.setObjectName("statusbar")
        JogodaForca.setStatusBar(self.statusbar)

        self.retranslateUi(JogodaForca)
        QtCore.QMetaObject.connectSlotsByName(JogodaForca)

    def retranslateUi(self, JogodaForca):
        _translate = QtCore.QCoreApplication.translate
        JogodaForca.setWindowTitle(_translate("JogodaForca", "Jogo da Forca"))
        self.labAlfabeto.setText(_translate("JogodaForca", "alfabeto"))
        self.labForca.setText(_translate("JogodaForca", "forca"))
        self.labErros.setText(_translate("JogodaForca", "erros"))
        self.btnA.setText(_translate("JogodaForca", "A"))
        self.btnB.setText(_translate("JogodaForca", "B"))
        self.btnG.setText(_translate("JogodaForca", "G"))
        self.btnF.setText(_translate("JogodaForca", "F"))
        self.btnC.setText(_translate("JogodaForca", "C"))
        self.btnD.setText(_translate("JogodaForca", "D"))
        self.btnE.setText(_translate("JogodaForca", "E"))
        self.btnH.setText(_translate("JogodaForca", "H"))
        self.btnO.setText(_translate("JogodaForca", "O"))
        self.btnN.setText(_translate("JogodaForca", "N"))
        self.btnL.setText(_translate("JogodaForca", "L"))
        self.btnM.setText(_translate("JogodaForca", "M"))
        self.btnP.setText(_translate("JogodaForca", "P"))
        self.btnJ.setText(_translate("JogodaForca", "J"))
        self.btnK.setText(_translate("JogodaForca", "K"))
        self.btnI.setText(_translate("JogodaForca", "I"))
        self.btnW.setText(_translate("JogodaForca", "W"))
        self.btnV.setText(_translate("JogodaForca", "V"))
        self.btnT.setText(_translate("JogodaForca", "T"))
        self.btnU.setText(_translate("JogodaForca", "U"))
        self.btnX.setText(_translate("JogodaForca", "X"))
        self.btnR.setText(_translate("JogodaForca", "R"))
        self.btnS.setText(_translate("JogodaForca", "S"))
        self.btnY.setText(_translate("JogodaForca", "Y"))
        self.btnQ.setText(_translate("JogodaForca", "Q"))
        self.btnZ.setText(_translate("JogodaForca", "Z"))

