# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_jogo_da_forca.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_JogodaForca(object):
    def setupUi(self, JogodaForca):
        JogodaForca.setObjectName("JogodaForca")
        JogodaForca.resize(816, 555)
        self.centralwidget = QtWidgets.QWidget(JogodaForca)
        self.centralwidget.setObjectName("centralwidget")
        self.labForca = QtWidgets.QLabel(self.centralwidget)
        self.labForca.setGeometry(QtCore.QRect(20, 30, 331, 381))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.labForca.setFont(font)
        self.labForca.setObjectName("labForca")
        self.labErros = QtWidgets.QLabel(self.centralwidget)
        self.labErros.setGeometry(QtCore.QRect(20, 11, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.labErros.setFont(font)
        self.labErros.setObjectName("labErros")
        self.btnA = QtWidgets.QPushButton(self.centralwidget)
        self.btnA.setGeometry(QtCore.QRect(70, 446, 45, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnA.setFont(font)
        self.btnA.setObjectName("btnA")
        self.btnB = QtWidgets.QPushButton(self.centralwidget)
        self.btnB.setGeometry(QtCore.QRect(120, 446, 44, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnB.setFont(font)
        self.btnB.setObjectName("btnB")
        self.btnG = QtWidgets.QPushButton(self.centralwidget)
        self.btnG.setGeometry(QtCore.QRect(370, 446, 44, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnG.setFont(font)
        self.btnG.setObjectName("btnG")
        self.btnF = QtWidgets.QPushButton(self.centralwidget)
        self.btnF.setGeometry(QtCore.QRect(320, 446, 45, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnF.setFont(font)
        self.btnF.setObjectName("btnF")
        self.btnC = QtWidgets.QPushButton(self.centralwidget)
        self.btnC.setGeometry(QtCore.QRect(170, 446, 45, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnC.setFont(font)
        self.btnC.setObjectName("btnC")
        self.btnD = QtWidgets.QPushButton(self.centralwidget)
        self.btnD.setGeometry(QtCore.QRect(220, 446, 44, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnD.setFont(font)
        self.btnD.setObjectName("btnD")
        self.btnE = QtWidgets.QPushButton(self.centralwidget)
        self.btnE.setGeometry(QtCore.QRect(270, 446, 44, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnE.setFont(font)
        self.btnE.setObjectName("btnE")
        self.btnH = QtWidgets.QPushButton(self.centralwidget)
        self.btnH.setGeometry(QtCore.QRect(420, 446, 45, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnH.setFont(font)
        self.btnH.setObjectName("btnH")
        self.btnO = QtWidgets.QPushButton(self.centralwidget)
        self.btnO.setGeometry(QtCore.QRect(120, 480, 44, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnO.setFont(font)
        self.btnO.setObjectName("btnO")
        self.btnN = QtWidgets.QPushButton(self.centralwidget)
        self.btnN.setGeometry(QtCore.QRect(70, 480, 45, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnN.setFont(font)
        self.btnN.setObjectName("btnN")
        self.btnL = QtWidgets.QPushButton(self.centralwidget)
        self.btnL.setGeometry(QtCore.QRect(620, 446, 44, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnL.setFont(font)
        self.btnL.setObjectName("btnL")
        self.btnM = QtWidgets.QPushButton(self.centralwidget)
        self.btnM.setGeometry(QtCore.QRect(670, 446, 44, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnM.setFont(font)
        self.btnM.setObjectName("btnM")
        self.btnP = QtWidgets.QPushButton(self.centralwidget)
        self.btnP.setGeometry(QtCore.QRect(170, 480, 45, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnP.setFont(font)
        self.btnP.setObjectName("btnP")
        self.btnJ = QtWidgets.QPushButton(self.centralwidget)
        self.btnJ.setGeometry(QtCore.QRect(520, 446, 44, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnJ.setFont(font)
        self.btnJ.setObjectName("btnJ")
        self.btnK = QtWidgets.QPushButton(self.centralwidget)
        self.btnK.setGeometry(QtCore.QRect(570, 446, 45, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnK.setFont(font)
        self.btnK.setObjectName("btnK")
        self.btnI = QtWidgets.QPushButton(self.centralwidget)
        self.btnI.setGeometry(QtCore.QRect(470, 446, 44, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnI.setFont(font)
        self.btnI.setObjectName("btnI")
        self.btnW = QtWidgets.QPushButton(self.centralwidget)
        self.btnW.setGeometry(QtCore.QRect(520, 480, 44, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnW.setFont(font)
        self.btnW.setObjectName("btnW")
        self.btnV = QtWidgets.QPushButton(self.centralwidget)
        self.btnV.setGeometry(QtCore.QRect(470, 480, 44, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnV.setFont(font)
        self.btnV.setObjectName("btnV")
        self.btnT = QtWidgets.QPushButton(self.centralwidget)
        self.btnT.setGeometry(QtCore.QRect(370, 480, 44, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnT.setFont(font)
        self.btnT.setObjectName("btnT")
        self.btnU = QtWidgets.QPushButton(self.centralwidget)
        self.btnU.setGeometry(QtCore.QRect(420, 480, 45, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnU.setFont(font)
        self.btnU.setObjectName("btnU")
        self.btnX = QtWidgets.QPushButton(self.centralwidget)
        self.btnX.setGeometry(QtCore.QRect(570, 480, 45, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnX.setFont(font)
        self.btnX.setObjectName("btnX")
        self.btnR = QtWidgets.QPushButton(self.centralwidget)
        self.btnR.setGeometry(QtCore.QRect(270, 480, 44, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnR.setFont(font)
        self.btnR.setObjectName("btnR")
        self.btnS = QtWidgets.QPushButton(self.centralwidget)
        self.btnS.setGeometry(QtCore.QRect(320, 480, 45, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnS.setFont(font)
        self.btnS.setObjectName("btnS")
        self.btnY = QtWidgets.QPushButton(self.centralwidget)
        self.btnY.setGeometry(QtCore.QRect(620, 480, 44, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnY.setFont(font)
        self.btnY.setObjectName("btnY")
        self.btnQ = QtWidgets.QPushButton(self.centralwidget)
        self.btnQ.setGeometry(QtCore.QRect(220, 480, 44, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnQ.setFont(font)
        self.btnQ.setObjectName("btnQ")
        self.btnZ = QtWidgets.QPushButton(self.centralwidget)
        self.btnZ.setGeometry(QtCore.QRect(670, 480, 44, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.btnZ.setFont(font)
        self.btnZ.setObjectName("btnZ")
        self.labPalavra = QtWidgets.QLabel(self.centralwidget)
        self.labPalavra.setGeometry(QtCore.QRect(300, 360, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.labPalavra.setFont(font)
        self.labPalavra.setObjectName("labPalavra")
        self.labLetra = QtWidgets.QLabel(self.centralwidget)
        self.labLetra.setGeometry(QtCore.QRect(700, 90, 71, 41))
        self.labLetra.setText("")
        self.labLetra.setObjectName("labLetra")
        JogodaForca.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JogodaForca)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 816, 22))
        self.menubar.setObjectName("menubar")
        JogodaForca.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JogodaForca)
        self.statusbar.setObjectName("statusbar")
        JogodaForca.setStatusBar(self.statusbar)

        self.retranslateUi(JogodaForca)
        QtCore.QMetaObject.connectSlotsByName(JogodaForca)

    def retranslateUi(self, JogodaForca):
        _translate = QtCore.QCoreApplication.translate
        JogodaForca.setWindowTitle(_translate("JogodaForca", "Jogo da Forca"))
        self.labForca.setText(_translate("JogodaForca", "forca"))
        self.labErros.setText(_translate("JogodaForca", "erros"))
        self.btnA.setText(_translate("JogodaForca", "A"))
        self.btnB.setText(_translate("JogodaForca", "B"))
        self.btnG.setText(_translate("JogodaForca", "G"))
        self.btnF.setText(_translate("JogodaForca", "F"))
        self.btnC.setText(_translate("JogodaForca", "C"))
        self.btnD.setText(_translate("JogodaForca", "D"))
        self.btnE.setText(_translate("JogodaForca", "E"))
        self.btnH.setText(_translate("JogodaForca", "H"))
        self.btnO.setText(_translate("JogodaForca", "O"))
        self.btnN.setText(_translate("JogodaForca", "N"))
        self.btnL.setText(_translate("JogodaForca", "L"))
        self.btnM.setText(_translate("JogodaForca", "M"))
        self.btnP.setText(_translate("JogodaForca", "P"))
        self.btnJ.setText(_translate("JogodaForca", "J"))
        self.btnK.setText(_translate("JogodaForca", "K"))
        self.btnI.setText(_translate("JogodaForca", "I"))
        self.btnW.setText(_translate("JogodaForca", "W"))
        self.btnV.setText(_translate("JogodaForca", "V"))
        self.btnT.setText(_translate("JogodaForca", "T"))
        self.btnU.setText(_translate("JogodaForca", "U"))
        self.btnX.setText(_translate("JogodaForca", "X"))
        self.btnR.setText(_translate("JogodaForca", "R"))
        self.btnS.setText(_translate("JogodaForca", "S"))
        self.btnY.setText(_translate("JogodaForca", "Y"))
        self.btnQ.setText(_translate("JogodaForca", "Q"))
        self.btnZ.setText(_translate("JogodaForca", "Z"))
        self.labPalavra.setText(_translate("JogodaForca", "palavra"))

