# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_jogo_da_forca.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_JogodaForca(object):
    def setupUi(self, JogodaForca):
        JogodaForca.setObjectName("JogodaForca")
        JogodaForca.setWindowModality(QtCore.Qt.NonModal)
        JogodaForca.setEnabled(True)
        JogodaForca.resize(920, 648)
        JogodaForca.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        JogodaForca.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        JogodaForca.setStyleSheet("")
        JogodaForca.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        JogodaForca.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(JogodaForca)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.labErros = QtWidgets.QLabel(self.centralwidget)
        self.labErros.setEnabled(True)
        self.labErros.setGeometry(QtCore.QRect(10, 14, 141, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labErros.sizePolicy().hasHeightForWidth())
        self.labErros.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setItalic(True)
        self.labErros.setFont(font)
        self.labErros.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/moldura.png\");\n"
"color: rgba(80,45,22,250);")
        self.labErros.setLineWidth(1)
        self.labErros.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labErros.setIndent(28)
        self.labErros.setObjectName("labErros")
        self.btnA = QtWidgets.QPushButton(self.centralwidget)
        self.btnA.setGeometry(QtCore.QRect(10, 480, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnA.setFont(font)
        self.btnA.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnA.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnA.setObjectName("btnA")
        self.btnB = QtWidgets.QPushButton(self.centralwidget)
        self.btnB.setGeometry(QtCore.QRect(80, 480, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnB.setFont(font)
        self.btnB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnB.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnB.setObjectName("btnB")
        self.btnG = QtWidgets.QPushButton(self.centralwidget)
        self.btnG.setGeometry(QtCore.QRect(430, 480, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnG.setFont(font)
        self.btnG.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnG.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnG.setObjectName("btnG")
        self.btnF = QtWidgets.QPushButton(self.centralwidget)
        self.btnF.setGeometry(QtCore.QRect(360, 480, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnF.setFont(font)
        self.btnF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnF.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnF.setObjectName("btnF")
        self.btnC = QtWidgets.QPushButton(self.centralwidget)
        self.btnC.setGeometry(QtCore.QRect(150, 480, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnC.setFont(font)
        self.btnC.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnC.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnC.setObjectName("btnC")
        self.btnD = QtWidgets.QPushButton(self.centralwidget)
        self.btnD.setGeometry(QtCore.QRect(220, 480, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnD.setFont(font)
        self.btnD.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnD.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnD.setObjectName("btnD")
        self.btnE = QtWidgets.QPushButton(self.centralwidget)
        self.btnE.setGeometry(QtCore.QRect(290, 480, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnE.setFont(font)
        self.btnE.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnE.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnE.setObjectName("btnE")
        self.btnH = QtWidgets.QPushButton(self.centralwidget)
        self.btnH.setGeometry(QtCore.QRect(500, 480, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnH.setFont(font)
        self.btnH.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnH.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnH.setObjectName("btnH")
        self.btnO = QtWidgets.QPushButton(self.centralwidget)
        self.btnO.setGeometry(QtCore.QRect(80, 540, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnO.setFont(font)
        self.btnO.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnO.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnO.setObjectName("btnO")
        self.btnN = QtWidgets.QPushButton(self.centralwidget)
        self.btnN.setGeometry(QtCore.QRect(10, 540, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnN.setFont(font)
        self.btnN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnN.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnN.setObjectName("btnN")
        self.btnL = QtWidgets.QPushButton(self.centralwidget)
        self.btnL.setGeometry(QtCore.QRect(780, 480, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnL.setFont(font)
        self.btnL.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnL.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnL.setObjectName("btnL")
        self.btnM = QtWidgets.QPushButton(self.centralwidget)
        self.btnM.setGeometry(QtCore.QRect(850, 480, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnM.setFont(font)
        self.btnM.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnM.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnM.setObjectName("btnM")
        self.btnP = QtWidgets.QPushButton(self.centralwidget)
        self.btnP.setGeometry(QtCore.QRect(150, 540, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnP.setFont(font)
        self.btnP.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnP.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnP.setObjectName("btnP")
        self.btnJ = QtWidgets.QPushButton(self.centralwidget)
        self.btnJ.setGeometry(QtCore.QRect(640, 480, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnJ.setFont(font)
        self.btnJ.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnJ.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnJ.setObjectName("btnJ")
        self.btnK = QtWidgets.QPushButton(self.centralwidget)
        self.btnK.setGeometry(QtCore.QRect(710, 480, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnK.setFont(font)
        self.btnK.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnK.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnK.setObjectName("btnK")
        self.btnI = QtWidgets.QPushButton(self.centralwidget)
        self.btnI.setGeometry(QtCore.QRect(570, 480, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnI.setFont(font)
        self.btnI.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnI.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnI.setObjectName("btnI")
        self.btnW = QtWidgets.QPushButton(self.centralwidget)
        self.btnW.setGeometry(QtCore.QRect(640, 540, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnW.setFont(font)
        self.btnW.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnW.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnW.setObjectName("btnW")
        self.btnV = QtWidgets.QPushButton(self.centralwidget)
        self.btnV.setGeometry(QtCore.QRect(570, 540, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnV.setFont(font)
        self.btnV.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnV.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnV.setObjectName("btnV")
        self.btnT = QtWidgets.QPushButton(self.centralwidget)
        self.btnT.setGeometry(QtCore.QRect(430, 540, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnT.setFont(font)
        self.btnT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnT.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnT.setObjectName("btnT")
        self.btnU = QtWidgets.QPushButton(self.centralwidget)
        self.btnU.setGeometry(QtCore.QRect(500, 540, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnU.setFont(font)
        self.btnU.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnU.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnU.setObjectName("btnU")
        self.btnX = QtWidgets.QPushButton(self.centralwidget)
        self.btnX.setGeometry(QtCore.QRect(710, 540, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnX.setFont(font)
        self.btnX.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnX.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnX.setObjectName("btnX")
        self.btnR = QtWidgets.QPushButton(self.centralwidget)
        self.btnR.setGeometry(QtCore.QRect(290, 540, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnR.setFont(font)
        self.btnR.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnR.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnR.setObjectName("btnR")
        self.btnS = QtWidgets.QPushButton(self.centralwidget)
        self.btnS.setGeometry(QtCore.QRect(360, 540, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnS.setFont(font)
        self.btnS.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnS.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnS.setObjectName("btnS")
        self.btnY = QtWidgets.QPushButton(self.centralwidget)
        self.btnY.setGeometry(QtCore.QRect(780, 540, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnY.setFont(font)
        self.btnY.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnY.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnY.setObjectName("btnY")
        self.btnQ = QtWidgets.QPushButton(self.centralwidget)
        self.btnQ.setGeometry(QtCore.QRect(220, 540, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnQ.setFont(font)
        self.btnQ.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnQ.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnQ.setObjectName("btnQ")
        self.btnZ = QtWidgets.QPushButton(self.centralwidget)
        self.btnZ.setGeometry(QtCore.QRect(850, 540, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnZ.setFont(font)
        self.btnZ.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnZ.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaoletra.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnZ.setObjectName("btnZ")
        self.labPalavra = QtWidgets.QLabel(self.centralwidget)
        self.labPalavra.setGeometry(QtCore.QRect(300, 390, 531, 51))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labPalavra.setFont(font)
        self.labPalavra.setStyleSheet("border-image: url(\"/home/ericdecastro/Área de Trabalho/desenho forca/caixatexto.png\");\n"
"color: rgba(80,45,22,250);")
        self.labPalavra.setIndent(40)
        self.labPalavra.setObjectName("labPalavra")
        self.btnFecha = QtWidgets.QPushButton(self.centralwidget)
        self.btnFecha.setEnabled(True)
        self.btnFecha.setGeometry(QtCore.QRect(860, 20, 41, 41))
        self.btnFecha.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnFecha.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaofechar.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnFecha.setText("")
        self.btnFecha.setObjectName("btnFecha")
        self.btnMini = QtWidgets.QPushButton(self.centralwidget)
        self.btnMini.setGeometry(QtCore.QRect(800, 33, 41, 16))
        self.btnMini.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMini.setStyleSheet("border-image:url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/botaomini.png\");\n"
"color: rgba(80,45,22,250);")
        self.btnMini.setText("")
        self.btnMini.setObjectName("btnMini")
        self.widgetFundo2 = QtWidgets.QWidget(self.centralwidget)
        self.widgetFundo2.setGeometry(QtCore.QRect(0, -15, 921, 481))
        self.widgetFundo2.setStyleSheet("border-image: url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/praça.png\");")
        self.widgetFundo2.setObjectName("widgetFundo2")
        self.labForca = QtWidgets.QLabel(self.widgetFundo2)
        self.labForca.setGeometry(QtCore.QRect(10, 160, 281, 291))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labForca.setFont(font)
        self.labForca.setAutoFillBackground(False)
        self.labForca.setStyleSheet("border-image: url(\"/home/ericdecastro/Área de Trabalho/desenho forca/forca.png\");")
        self.labForca.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labForca.setLineWidth(1)
        self.labForca.setText("")
        self.labForca.setObjectName("labForca")
        self.pushButton = QtWidgets.QPushButton(self.widgetFundo2)
        self.pushButton.setGeometry(QtCore.QRect(850, 400, 61, 61))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("border-image:url(\"/home/ericdecastro/Área de Trabalho/desenho forca/volume ligado2.png\");")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.widgetFundo = QtWidgets.QWidget(self.centralwidget)
        self.widgetFundo.setGeometry(QtCore.QRect(0, 466, 921, 151))
        self.widgetFundo.setStyleSheet("border-image: url(\"/home/ericdecastro/PycharmProjects/Python_udemy/Jogo_da_forca1/fundomadeira.png\");\n"
"")
        self.widgetFundo.setObjectName("widgetFundo")
        self.widgetFundo.raise_()
        self.widgetFundo2.raise_()
        self.labErros.raise_()
        self.btnA.raise_()
        self.btnB.raise_()
        self.btnG.raise_()
        self.btnF.raise_()
        self.btnC.raise_()
        self.btnD.raise_()
        self.btnE.raise_()
        self.btnH.raise_()
        self.btnO.raise_()
        self.btnN.raise_()
        self.btnL.raise_()
        self.btnM.raise_()
        self.btnP.raise_()
        self.btnJ.raise_()
        self.btnK.raise_()
        self.btnI.raise_()
        self.btnW.raise_()
        self.btnV.raise_()
        self.btnT.raise_()
        self.btnU.raise_()
        self.btnX.raise_()
        self.btnR.raise_()
        self.btnS.raise_()
        self.btnY.raise_()
        self.btnQ.raise_()
        self.btnZ.raise_()
        self.labPalavra.raise_()
        self.btnFecha.raise_()
        self.btnMini.raise_()
        JogodaForca.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JogodaForca)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 22))
        self.menubar.setObjectName("menubar")
        JogodaForca.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JogodaForca)
        self.statusbar.setObjectName("statusbar")
        JogodaForca.setStatusBar(self.statusbar)

        self.retranslateUi(JogodaForca)
        QtCore.QMetaObject.connectSlotsByName(JogodaForca)

    def retranslateUi(self, JogodaForca):
        _translate = QtCore.QCoreApplication.translate
        JogodaForca.setWindowTitle(_translate("JogodaForca", "Jogo da Forca"))
        self.labErros.setText(_translate("JogodaForca", "<html><head/><body><p>erros</p></body></html>"))
        self.btnA.setText(_translate("JogodaForca", "A"))
        self.btnB.setText(_translate("JogodaForca", "B"))
        self.btnG.setText(_translate("JogodaForca", "G"))
        self.btnF.setText(_translate("JogodaForca", "F"))
        self.btnC.setText(_translate("JogodaForca", "C"))
        self.btnD.setText(_translate("JogodaForca", "D"))
        self.btnE.setText(_translate("JogodaForca", "E"))
        self.btnH.setText(_translate("JogodaForca", "H"))
        self.btnO.setText(_translate("JogodaForca", "O"))
        self.btnN.setText(_translate("JogodaForca", "N"))
        self.btnL.setText(_translate("JogodaForca", "L"))
        self.btnM.setText(_translate("JogodaForca", "M"))
        self.btnP.setText(_translate("JogodaForca", "P"))
        self.btnJ.setText(_translate("JogodaForca", "J"))
        self.btnK.setText(_translate("JogodaForca", "K"))
        self.btnI.setText(_translate("JogodaForca", "I"))
        self.btnW.setText(_translate("JogodaForca", "W"))
        self.btnV.setText(_translate("JogodaForca", "V"))
        self.btnT.setText(_translate("JogodaForca", "T"))
        self.btnU.setText(_translate("JogodaForca", "U"))
        self.btnX.setText(_translate("JogodaForca", "X"))
        self.btnR.setText(_translate("JogodaForca", "R"))
        self.btnS.setText(_translate("JogodaForca", "S"))
        self.btnY.setText(_translate("JogodaForca", "Y"))
        self.btnQ.setText(_translate("JogodaForca", "Q"))
        self.btnZ.setText(_translate("JogodaForca", "Z"))
        self.labPalavra.setText(_translate("JogodaForca", "palavra"))

