animais = ['abelha', 'abutre', 'águia', 'alce', 'anaconda', 'andorinha', 'anta', 'aranha', 'arara', 'avestruz',
           'babuíno', 'bacalhau', 'baiacu', 'baleia', 'barata', 'besouro', 'bezerro', 'bode', 'borboleta', 'búfalo',
           'burro', 'cabra', 'cachorro', 'camaleão', 'camarão', 'camelo', 'camundongo', 'canguru', 'capivara',
           'caracol', 'caranguejo', 'carneiro', 'castor', 'cavalo', 'cegonha', 'centopeia', 'chimpanzé', 'chinchila',
           'cigarra', 'cisne', 'coala', 'cobra', 'coelho', 'coiote', 'coruja', 'corvo', 'crocodilo', 'cupim',
           'dinossauro', 'égua', 'elefante', 'enguia', 'escorpião', 'esquilo', 'falcão', 'flamingo', 'foca', 'formiga',
           'furão', 'gafanhoto', 'gaivota', 'galinha', 'galo', 'gambá', 'ganso', 'garça', 'gato', 'gavião', 'gazela',
           'girafa', 'girino', 'golfinho', 'gorila', 'grilo', 'guaxinim', 'hamster', 'hiena', 'hipopótamo', 'iguana',
           'jacaré', 'javali', 'joaninha', 'jumento', 'lagarta', 'lagartixa', 'lagarto', 'lagosta', 'leão', 'lebre',
           'leopardo', 'lesma', 'lhama', 'libélula', 'lince', 'lobo', 'lontra', 'lula', 'macaco', 'mamute',
           'marimbondo', 'mariposa', 'marisco', 'marmota', 'medusa', 'minhoca', 'morcego', 'morsa', 'mosca', 'mosquito',
           'onça', 'orangotango', 'ornitorrinco', 'ostra', 'ouriço', 'ovelha', 'panda', 'pantera', 'papagaio', 'pardal',
           'pássaro', 'pato', 'pavão', 'peixe', 'pelicano', 'periquito', 'pernilongo', 'peru', 'pinguim', 'polvo',
           'pombo', 'pônei', 'porco', 'preguiça', 'pulga', 'raposa', 'rato', 'rena', 'rinoceronte', 'salamandra',
           'salmão', 'sanguessuga', 'sapo', 'serpente', 'siri', 'tamanduá', 'tarântula', 'tartaruga', 'tatu', 'texugo',
           'tigre', 'toupeira', 'touro', 'truta', 'tubarão', 'tucano', 'urso', 'panda', 'urubu', 'vaca', 'veado',
           'vespa', 'víbora', 'vieira', 'vitela', 'zebra']


profissoes = ['açougueiro', 'advogado', 'aeromoça', 'atleta', 'astrônomo', 'astronauta', 'atendente', 'assessora',
              'artesão', 'arquiteto', 'arquivista', 'ator', 'biólogo', 'bibliotecária', 'balconista', 'barbeiro',
              'bancário', 'babá', 'carteiro', 'cirurgião', 'cientista', 'carpinteiro', 'costureira', 'compositor',
              'cabeleireiro', 'caixa', 'cantor', 'designer', 'diretor', 'dublê', 'dublador', 'diarista', 'deputado',
              'delegado', 'dermatologista', 'desenhista', 'desembargador', 'engenheiro', 'empacotador', 'enfermeira',
              'encanador', 'empresário', 'eletricista', 'estilista', 'estoquista', 'farmacêutico', 'feirante',
              'faxineira', 'físico', 'ferreiro', 'fiscal', 'florista', 'fonoaudiólogo', 'fisioterapeuta', 'fotógrafo',
              'garçom', 'governador', 'governanta', 'geriatra', 'ginecologista', 'guarda', 'gerente', 'historiador',
              'ilustrador', 'inspetor', 'instrutor', 'investigador', 'infectologista', 'jardineiro', 'jogador',
              'jornalista', 'jornaleiro', 'juiz', 'lavrador', 'legista', 'lixeiro', 'locutor', 'lutador', 'lenhador',
              'marceneiro', 'maestro', 'matemático', 'músico', 'motorista', 'metalúrgico', 'médico', 'mecânico',
              'maquiadora', 'massagista', 'maquinista', 'manicure', 'nadador', 'nutricionista', 'neurologista',
              'numerólogo', 'neurocirurgião', 'oftalmologista', 'oculista', 'ortodontista', 'obstetra', 'paraquedista',
              'paramédico', 'pescador', 'perito', 'pintor', 'pianista', 'pizzaiolo', 'publicitário', 'psicólogo',
              'personal trainer', 'piloto', 'político', 'prefeito', 'presidente', 'programador', 'químico',
              'quitandeiro', 'quadrinista', 'roteirista', 'repórter', 'recepcionista', 'radiologista', 'senador',
              'sonoplasta', 'sociólogo', 'soldado', 'sargento', 'sapateiro', 'taxista', 'tabelião', 'tenente',
              'terapeuta', 'tatuador', 'trapezista', 'urologista', 'urbanista', 'vigilante', 'veterinário', 'vendedor',
              'vigia', 'vereador', 'web designer', 'zoólogo', 'zelador']

objetos = ['agulha', 'alfinete', 'anel', 'anzol', 'apontador', 'almofada', 'abajur', 'bola', 'balão', 'botas',
           'bexiga', 'borracha', 'batom', 'cola', 'colher', 'caneta', 'camisa', 'camiseta', 'camisola', 'calça', 'copo',
           'carimbo', 'câmera', 'cachecol', 'dado', 'dedal', 'dicionário', 'diário', 'diamante', 'dentadura', 'disco',
           'desentupidor', 'delineador', 'depilador', 'escada', 'escova', 'espelho', 'espada', 'espátula', 'esmalte',
           'faca', 'facão', 'folha', 'furadeira', 'ferradura', 'funil', 'farol', 'gaiola', 'garfo', 'garrafa', 'gaveta',
           'guitarra', 'gaita', 'gravata', 'gorro', 'hidratante', 'hélice', 'holofote', 'isqueiro', 'isopor', 'isca',
           'inalador', 'incenso', 'insecticida', 'jarra', 'jóias', 'jaqueta', 'janela', 'lápis', 'luvas', 'lampada',
           'luminária', 'leque', 'lenço', 'livro', 'lanterna', 'lixeira', 'lapiseira', 'lata', 'maquiagem', 'meias',
           'mala', 'mochila', 'maçarico', 'navalha', 'novelo', 'óculos', 'panela', 'pedra', 'papel', 'pen drive',
           'prato', 'pulseira', 'queijeira', 'quadro', 'régua', 'ratoeira', 'roleta', 'relógio', 'remo', 'roteador',
           'revista', 'sandália', 'sapato', 'saleiro', 'sino', 'sacola', 'sabonete', 'shorts', 'tesoura', 'teclado',
           'telefone', 'tampa', 'termômetro', 'trena', 'telha', 'tatame', 'tamanco', 'urna', 'ursinho de pelúcia',
           'uniforme', 'umidificador de ar', 'vassoura', 'ventilador', 'vara de pescar', 'varal', 'vaso', 'vidro',
           'vela', 'xícara', 'xale', 'xarope', 'zíper']

paises = ['afeganistão', 'áfrica do sul', 'albânia', 'alemanha', 'angola', 'arábia saudita', 'argélia', 'argentina',
          'armênia', 'aruba', 'austrália', 'áustria', 'azerbaijão', 'bangladesh', 'barbados', 'bélgica', 'bermudas',
          'bielorrússia', 'bolívia', 'bósnia e herzegovina', 'botsuana', 'brasil', 'bulgária', 'butão', 'camarões',
          'camboja', 'canadá', 'cazaquistão', 'chile', 'china', 'chipre', 'colômbia', 'coreia do norte',
          'coreia do sul', 'costa do marfim', 'costa rica', 'croácia', 'cuba', 'dinamarca', 'egito', 'equador',
          'eslováquia', 'eslovénia', 'espanha', 'estados unidos', 'estônia', 'etiópia', 'fiji', 'filipinas',
          'finlândia', 'frança', 'gana', 'grécia', 'groenlândia', 'guatemala', 'guiana', 'guiana francesa', 'haiti',
          'honduras', 'hong kong', 'hungria', 'iémen', 'índia', 'indonésia', 'iran', 'iraque', 'irlanda', 'islândia',
          'israel', 'itália', 'jamaica', 'japão', 'jordânia', 'kosovo', 'kuwait', 'laos', 'letônia', 'líbano',
          'libéria', 'líbia', 'lituânia', 'luxemburgo', 'macedônia', 'madagáscar', 'malásia', 'maldivas', 'malta',
          'marrocos', 'méxico', 'moçambique', 'mónaco', 'mongólia', 'montenegro', 'namíbia', 'nepal', 'nicarágua',
          'nigéria', 'noruega', 'nova zelândia', 'panamá', 'paquistão', 'paraguai', 'peru', 'polinésia francesa',
          'polônia', 'porto rico', 'portugal', 'quênia', 'qatar', 'república dominicana', 'romênia', 'ruanda', 'rússia',
          'senegal', 'serra leoa', 'sérvia', 'singapura', 'síria', 'somália', 'sri lanka', 'sudão', 'suécia', 'suíça',
          'suriname', 'tailândia', 'taiwan', 'tanzânia', 'tunísia', 'turcomenistão', 'turquia', 'ucrânia', 'uganda',
          'uruguai', 'uzbequistão', 'vaticano', 'venezuela', 'vietnam', 'zâmbia', 'zimbabué']
